apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia2
  template:
    metadata:
      labels:
        app: kubia2
    spec:
      containers:
      - name: kubia2
        image: shouhai/kubia2
